### ISSUE TITLE
hv.objects not found ¿? 

### ISSUE THREAD

**Issue by CarloCattano** [enzienaudio/heavylib#17]
" c:\Python27\python.exe hvcc.py main.pd -n noiseRevX -g unity -o ./noiseRev11/
  1) Error pd2hv: main.pd in "main.pd" @ (x:0, y:0): Don't know how to parse object "hv.reverb". Is it an object supported by Heavy? Is it an abstraction? Have the search paths been correctly configured?
  2) Error pd2hv: main.pd in "main.pd" @ (x:0, y:0): Don't know how to parse object "vline~". Is it an object supported by Heavy? Is it an abstraction? Have the search paths been correctly configured?"

**Tried to add to the path the heavylib-master but still doest compile .**

**Comment by CarloCattano** [comment]
**just found at -p "[~/Workspace/Projects/Enzien/heavylib/, ~/Desktop/myLib/]" **

**Comment by CarloCattano** [comment]
**Keeps giving error with:**
 c:\Python27\python.exe hvcc.py main.pd -o /revNOIZ/ -n REVnoiZ -p [C:/Users/x/Documents/Pd/externals/heavylib/]

**Outputs:**
 1) Error pd2hv: main.pd in "main.pd" @ (x:0, y:0): Don't know how to parse object "hv.reverb". Is it an object supported by Heavy? Is it an abstraction? Have the search paths been correctly configured?
  2) Error pd2hv: main.pd in "main.pd" @ (x:0, y:0): Don't know how to parse object "Hv.vline". Is it an object supported by Heavy? Is it an abstraction? Have the search paths been correctly configured?
  3) Error pd2hv: main.pd in "main.pd" @ (x:0, y:0): There was an error while connecting two objects. Have all objects been correctly instantiated? Have all inlets and outlets been declared?
  4) Error pd2hv: main.pd in "main.pd" @ (x:0, y:0): There was an error while connecting two objects. Have all objects been correctly instantiated? Have all inlets and outlets been declared?
  5) Error pd2hv: main.pd in "main.pd" @ (x:0, y:0): There was an error while connecting two objects. Have all objects been correctly instantiated? Have all inlets and outlets been declared?
  6) Error pd2hv: [comment text] in "main.pd" @ (x:0, y:0): Connection made to non-existent inlet at [comment {u'text': 'null object placeholder (hv.reverb)'}]:0.
  7) Error pd2hv: [comment text] in "main.pd" @ (x:0, y:0): Connection made to non-existent inlet at [comment {u'text': 'null object placeholder (Hv.vline)'}]:0.

**Comment by giuliomoro** [comment]
A few basic things that you may have overlooked:

* Did you try `-p [C:\Users\x\Documents\Pd\externals\heavylib]`? No idea how sensitive `python` * or this script) is to `/` vs `\` on Windows.
* Is `x` your actual username on the machine? Or did you replace it appropriately when running your script?
* more to the point, does `dir C:\Users\x\Documents\Pd\externals\heavylib\hv.reverb.pd` (with the appropriate username substitution) show the actual file?
* probably unrelated - you seem to be missing a `.` before the `/revNOIZ/`.
* should there be quotes around the`[...]`? No idea what shell you are using, but better be safe!
* if you copy the `.pd` files from `heavylib` inside the folder that contains `main.pd`, does it compile ok?

**Comment by CarloCattano** [comment]
> more to the point, does dir C:\Users\x\Documents\Pd\externals\heavylib\hv.reverb.pd 
### yes it does open the file
### X is my machine User name yes.
**Tried with and without quotes , slashes in other direction etc, still cant :-(
used [""] as seen in the example command in the docs :** 
-p "[~/Workspace/Projects/Enzien/heavylib/, ~/Desktop/myLib/]"

### Actuall corrected command (this time from command prompt instead of Cmder):
C:\Python27\python.exe C:\Users\x\Documents\Pd\hvcc\hvcc.py C:\Users\x\Documents\Pd\hvcc\main.pd -o C:\reverbTest\ -n reverbTest -p [C:\Users\x\Documents\Pd\externals\heavylib] -g unity

**Comment by giuliomoro** [comment]
> if you copy the .pd files from heavylib inside the folder that contains main.pd, does it compile ok?

**Comment by CarloCattano** [comment]
Solved . As you mentioned , i copied all the files to the hvcc folder (its making it so messy but working)
apparently the problem was : 
 [91mError[0m pd2hv: main.pd in "main.pd" @ (x:0, y:0): Don't know how to parse object **"vline~".** I

**I checked inside the hv.reverb help file , found a vline~ , replaced it with a line object**
**Cant find anymore the old list of supported objects as it was in the website , but im quite sure that vline~ was causing problem **
**When copying the files onto the folder there is no nee of setting the path with -p**

**Tested now with -p , and it works ! , its a problem within the hv_helpfiles that uses unsupported objects , gona read more carefully the logs in future!**

**Comment by CarloCattano** [comment]
**last command** 
c:\Python27\python.exe C:\Users\x\Documents\Pd\hvcc\hvcc.py C:\Users\x\Documents\Pd\hvcc\main.pd -o C:/reverbTest/ -n reverbTest -p [C:\Users\x\Documents\Pd\externals\heavylib] -g unity

**Where can I see the list of supported vanilla objects ? link is broken** [https://enzienaudio.com/docs/pdobjects.html](url)
**Should I post this issue on the hvcc . Thanks for the help and for releasing this open source**

**Comment by giuliomoro** [comment]
> Should I post this issue on the hvcc 

You have seen there that I point to two folders containing the supported objects. There is no official list as of now.

> I checked inside the hv.reverb help file , found a vline~ , replaced it with a line object

that's weird. `heavylib` provides a `hv.vline.pd` which is to be used as an almost drop-in replacement for `[vline~]`. Maybe on their build server they used to have an extra pre-processing step that would turn all the instances of `[vline~]` into `[hv.vline]`?

> for releasing this open source

I didn't do that, I am not affiliated with enzienaudio. Thanks to them.

**Comment by giuliomoro** [comment]
Here are some details on how `[hv.vline]` differs slightly from `[vline~]` : [https://github.com/enzienaudio/heavylib/issues/5](https://github.com/enzienaudio/heavylib/issues/5)

**Comment by CarloCattano** [comment]
Its definately there . Hv_reverb help file . A plain vline~ that was causing trouble .
Will do further testing and see

**Comment by CarloCattano** [comment]
Will post in the hvcc repo later on . I still couldnt use " -p " withouth errors . Im forced to put all the folders of heavylib on the same folder as the main.pd and the hvcc.py
